project:
  type: website

website:
  title: "Health Data Science Handbook"

  navbar:
    left:
      - href: index.qmd
        text: Inicio

      - href: about.qmd
        text: Sobre el proyecto

      - href: foundations/index.qmd
        text: Fundamentos

  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Inicio

      - href: about.qmd
        text: Sobre el proyecto

      - section: "Fundamentos"
        contents:
          - href: foundations/index.qmd
            text: Introducción
          - href: foundations/data-exploration.qmd
            text: Exploratory data analysis (EDA)

      - section: "Preprocesamiento"
        contents:
          - href: preprocessing/index.qmd
            text: Introducción

          - href: preprocessing/train-test-split.qmd
            text: Train, validation and test

          - href: preprocessing/data-leakage.qmd
            text: Data leakage

          - href: preprocessing/missing-data.qmd
            text: Valores ausentes

          - href: preprocessing/scaling-normalization.qmd
            text: Escalado y normalización

          - href: preprocessing/categorical-encoding.qmd
            text: Variables categóricas y encoding

          - href: preprocessing/outliers.qmd
            text: Outliers

      - section: "Reducción de dimensionalidad"
        contents:
          - href: dimensionality-reduction/index.qmd
            text: Introducción

          - href: dimensionality-reduction/pca.qmd
            text: PCA

      - section: "Aprendizaje supervisado"
        contents:
          - href: supervised-learning/index.qmd
            text: Introducción

      - section: "Aprendizaje no supervisado"
        contents:
          - href: unsupervised-learning/index.qmd
            text: Introducción

      - section: "Series temporales"
        contents:
          - href: time-series/index.qmd
            text: Introducción

      - section: "Deep learning"
        contents:
          - href: deep-learning/index.qmd
            text: Introducción

      - section: "Guías de proyectos"
        contents:
          - href: project-guides/index.qmd
            text: Introducción

      - section: "Recetario de código"
        contents:
          - href: code-recipes/index.qmd
            text: Introducción

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: false
    anchor-sections: false
