project:
  type: website

website:
  title: "Health Data Science Handbook"

  navbar:
    left:
      - href: index.qmd
        text: Inicio

      - href: about.qmd
        text: Sobre el proyecto

      - href: foundations/index.qmd
        text: Fundamentos

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Inicio

      - href: about.qmd
        text: Sobre el proyecto

      - section: "Fundamentos"
        contents:
          - href: foundations/index.qmd
            text: Introducción

          - href: foundations/data-exploration.qmd
            text: Exploración de datos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: false